<a href="https://colab.research.google.com/github/yesyell/DA_School_1/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%20%ED%95%B8%EB%93%A4%EB%A7%81/Numpy_%EB%B3%B5%EC%8A%B5%EC%98%88%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 연습 문제

In [3]:
import numpy as np

In [ ]:
# 1. 주어진 여러 개의 1차원 배열을 연결하여 하나의 큰 1차원 배열로 반환하세요.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9, 10])

arr_a = np.concatenate([arr1, arr2, arr3], axis=0)
print(arr_a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# 2. 주어진 2차원 배열에서 각 열의 평균값을 계산하여 새로운 1차원 배열로 나타내세요.

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
m = np.mean(arr, axis=0)
print(m)

[4. 5. 6.]


In [ ]:
# 3. 주어진 2차원 배열에서 각 행의 최대값을 구하여 1차원 배열로 반환하세요.

max = np.max(arr, axis=1)
print(max)

[3 6 9]


In [ ]:
# 4. 0에서 1사이의 값으로 크기 10개의 1차원 배열을 만들어주세요.

l = np.linspace(0, 1, 10)
print(l)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
# 5. 주어진 1차원 배열에서 짝수인 요소들의 합을 계산하는 함수 sum_of_evens를 작성하세요.

def sum_of_evens(arr: np.ndarray) -> int:
    arr_e = arr[arr % 2 == 0]  # 짝수인 요소 선택
    return np.sum(arr_e)  # 짝수인 요소들의 합 반환

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(sum_of_evens(arr))

30


In [ ]:
# 6. 수평분할, 수직분할, 수평 스택, 수직 스택 문제를 풀어봅시다.

# 분할할 배열 생성
arr = np.arange(1, 13).reshape((3, 4))
print("원본 배열:")
print(arr)
print('-'*10)

# 1. 수평분할하기 -> 다시 원본으로 스택쌓기
arr_split = np.hsplit(arr, 2)
print("수평 분할 결과:")
print(arr_split)
arr_1 = arr_split[0]
arr_2 = arr_split[1]
arr_stack = np.hstack((arr_1, arr_2))
print()
print(arr_stack)
print('-'*10)

# 2. 수직분할하기 -> 다시 원본으로 스택쌓기
arr_split = np.vsplit(arr, 3)
print("수직 분할 결과:")
print(arr_split)
arr_1 = arr_split[0]
arr_2 = arr_split[1]
arr_3 = arr_split[2]
arr_stack = np.vstack((arr_1, arr_2, arr_3))
print()
print(arr_stack)

원본 배열:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------
수평 분할 결과:
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------
수직 분할 결과:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 7. 배열에서 조건에 맞는 값 반환하는 문제를 풀어봅시다.

# 조건 : 값을 10으로 나누었을 때 나머지가 0이면 원래 값 출력, 아니면 0으로 출력하세요.
arr = np.arange(0, 100, 5).reshape((5,4))
print(arr)

arr1 = np.where(arr % 10 == 0, arr, 0)
print(arr1)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]
 [80 85 90 95]]
[[ 0  0 10  0]
 [20  0 30  0]
 [40  0 50  0]
 [60  0 70  0]
 [80  0 90  0]]


In [ ]:
# 8. [3x3]배열 lst 중 짝수만 뽑아내는 부울린 인덱싱 배열(numpy 배열)을 사용하여 짝수 배열 n 을 만드시오.

lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
a = np.array(lst)

n = a[a%2 == 0]
print(n)

[2 4 6 8]


In [ ]:
# 인덱싱 배열을 이용하기
bool_indexing_array = np.array([
    [False,  True, False],
    [True, False,  True],
    [False,  True, False]
])
n = a[bool_indexing_array]
print(n)    

# 배열 a 에 대해 짝수면 True, 홀수면 False 
bool_indexing = (a % 2 == 0)
print(bool_indexing)
print(a[bool_indexing])

[2 4 6 8]
[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


In [ ]:
# 9. 각도를 이용해서 삼각함수를 만들어봅시다.

angle = np.pi / 3 # 라디안 표기 = 60도 
# 360도는 2라디안 으로, 180도는 1라디안으로 표현합니다.

sin_ = np.sin(angle)
cos_ = np.cos(angle)
tan_ = np.tan(angle)
print(sin_)
print(cos_)
print(tan_)

0.8660254037844386
0.5000000000000001
1.7320508075688767


In [ ]:
# 10. 조건함수를 사용해서 짝수조건을 만족하는 요소의 값이 2배로 만드는 배열을 만드시오.

arr = np.array([1, 2, 3, 4, 5])
arr1 = np.where(arr % 2 == 0, arr * 2, arr)
print(arr1)

[1 4 3 8 5]


---
### 배열

- 사이즈 10의 Null(0) 1차원 배열을 만들어보세요.

In [ ]:
import numpy as np

z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


차원 만드는 넘파이 함수를 사용해보겠습니다.
- 값이 10 ~ 49 인 1차원 배열을 만들어주세요.

In [ ]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


0~8 까지의 값을 사용하여 `3x3` 배열을 만드시오

In [ ]:
z = np.arange(9).reshape(3, 3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


(응용) 5x5 배열을 만들어서 경계값만 1이고, 내부에 있는 값은 0 인 2차원 배열을 만들어 보세요


In [ ]:
z = np.ones((5, 5))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 랜덤

오늘 배운 랜덤함수를 사용해서 문제를 풀어보겠습니다.

- 랜덤 값이 있는 `3x3x3` array 만들기

In [ ]:
z = np.random.random((3, 3, 3))
print(z)

[[[0.46494354 0.58852373 0.21824137]
  [0.86725324 0.40587558 0.49542955]
  [0.78811284 0.3771192  0.18354424]]

 [[0.78326835 0.66662515 0.75724472]
  [0.69798059 0.69236159 0.73827868]
  [0.21917873 0.68375842 0.80602026]]

 [[0.58825094 0.38180993 0.33330427]
  [0.0154524  0.57367666 0.65817057]
  [0.55316377 0.32820305 0.11910533]]]


랜덤 값이 있는 `10x10` 배열을 만들고 최소값과 최대값을 찾아주세요

In [ ]:
z = np.random.random((10, 10))
print(z.min(), z.max())

0.007472542908793844 0.974699747379136


30 크기의 랜덤 값을 가지는 1차원 배열을 만들어서 평균값을 도출해주세요.

In [ ]:
z = np.random.random(30)
print(z)
print(z.mean())

[0.43618332 0.98066981 0.51078018 0.54342433 0.07415463 0.98032963
 0.88306142 0.08241015 0.09660413 0.81599901 0.46697666 0.06102785
 0.18853163 0.70399153 0.88655465 0.36728862 0.01302452 0.00602524
 0.06429726 0.08432796 0.41726318 0.26608685 0.61460982 0.34124367
 0.30748227 0.48787387 0.16714526 0.308764   0.39677689 0.43477112]
0.399589315286593


### 행렬

행렬 연산을 해보겠습니다.
- 1로 채워진 `5x3` 행렬과 `3x2` 행렬의 곱을 구해봅니다.

[행렬 곱](https://blog.naver.com/cni1577/221754216275)

In [ ]:
x = np.ones((5, 3))
print(x)
y = np.ones((3, 2))
print(y)
print()
z = np.dot(x, y)
# z = x @ y
print(z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


(응용) 행렬의 연산을 하고 제로행렬 C에 값을 덮어씌워주세요.
- np.add() 함수의 매개변수를 응용합니다. 

In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.zeros(3)

np.add(A, B, out=C)
# C = np.add(A, B)
print(C)

[5. 7. 9.]


(응용) A 배열의 모든 요소의 부호를 반전시켜서 C에 값을 덮어씌워주세요.
- np.negative()

In [ ]:
np.negative(A, out=C)
print(C)

[-1. -2. -3.]


크기 10개의 1차원 랜덤 행렬을 만들고 최대값을 0 으로 바꾸어 주세요
1. 최대값이 어디에 있는 지 인덱스를 확인하면
2. 인덱싱을 통해서 최대값을 0으로 바꿔줄 수 있습니다.
3. argmax() 함수는 배열의 요소들 중에서 가장 큰 값이 있는 위치의 인덱스를 반환합니다.

In [ ]:
z = np.random.random(10)

max_i = z.argmax()
z[max_i] = 0

print(f'최대값이 있는 인덱스: {max_i}')
print(z)

최대값이 있는 인덱스: 1
[0.53496713 0.         0.00530629 0.59139005 0.57133258 0.50269353
 0.54223343 0.60677806 0.723845   0.25560574]


np.max 와 np.argmax 의 값을 확인해봅시다.

- 각 열과 행별로 최댓값을 반환하고 인덱스를 호출해주세요



In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('arr에서 최댓값:', np.max(arr))
print('arr에서 최댓값인 6이 위치한 인덱스:',np.argmax(arr))
print('arr에서 각 열(axis=0)별로 최댓값을 반환:', np.max(arr, axis=0))
print('arr에서 각 행(axis=1)별로 최댓값을 반환:', np.max(arr, axis=1))
print('arr에서 각 열(axis=0)별로 최댓값의 인덱스를 반환:',np.argmax(arr, axis=0))
print('arr에서 각 행(axis=1)별로 최댓값의 인덱스를 반환:',np.argmax(arr, axis=1))

arr에서 최댓값: 6
arr에서 최댓값인 6이 위치한 인덱스: 5
arr에서 각 열(axis=0)별로 최댓값을 반환: [4 5 6]
arr에서 각 열(axis=1)별로 최댓값을 반환: [3 6]
arr에서 각 행(axis=0)별로 최댓값의 인덱스를 반환: [1 1 1]
arr에서 각 행(axis=1)별로 최댓값의 인덱스를 반환: [2 2]


## 형변환
- 균일분포의 랜덤함수를 이용해서 0 ~ 100 까지 값을 가지는 1차원 **실수 (32비트)** 행렬을 만듭니다.
- **정수 (32비트)** 이면서 배열의 모양을 `10x1` 로 변환해주세요 

`view()` 함수와 `astype()` 함수는 NumPy 배열에서 각각 다른 목적을 가지고 사용되는 함수입니다.

In [11]:
f = (np.random.rand(10)*100).astype(np.float32)
# f = np.random.uniform(0, 100, 10).astype(np.float32)

print(f)
print(f.dtype)

[52.081974 87.52822  14.526984 86.220505 40.175564 63.680122  7.139843
 63.191708 85.983116 21.77151 ]
float32


In [12]:
i = f.view(np.int32)
i.shape = (10, 1)
# i = np.int32(f).reshape((10, 1))
print(i)
print(i.dtype)

[[1112560625]
 [1118768755]
 [1097363079]
 [1118597350]
 [1109439431]
 [1115601010]
 [1088715160]
 [1115472975]
 [1118566235]
 [1101933581]]
int32


집계 함수로 배열에 Null 값이 있는지 확인해보세요.
- 정수형 난수로 `3x10` 행렬을 생성합니다.
- 0 ~ 5 까지의 값으로 만들어주세요.

In [ ]:
z = np.random.randint(0, 6, size=(3, 10))
print(z)
print(z.any()) # == np.any(z)

[[0 5 4 5 0 1 1 1 4 4]
 [1 1 3 1 5 1 2 4 3 4]
 [5 1 0 5 5 1 4 1 2 1]]
True


## 정규분포, 균일분포


정규분포 normal()을 따르는 난수 생성의 방법을 배웠습니다.
이번에는 주어진 범위에서 균일분포를 따르는 난수 생성을 해보겠습니다.

- Normal Distribution
- Uniform Distribution





> [low, high] 범위에서 균일 분포를 따르는 난수 생성


> `random_number = np.random.uniform(low, high, size)`

(응용) 0부터 1사이의 10개의 값을 가지는 균일분포 배열을 만들어주세요
- 배열에서 지정된 값에서 가장 가까운 값을 찾겠습니다. => 정답 인덱스 호출 => 가장 가까운 값 호출
- num = 0.5 








In [14]:
z = np.random.uniform(0, 1, 10)
# z = np.random.rand(10)
print(z)

num = 0.5
i = np.abs(z-num).argmin()
print(i)
print(z[i])

[0.36384666 0.13707865 0.34322051 0.42880475 0.80653295 0.94599219
 0.18612309 0.04740545 0.03858992 0.33325161]
3
0.4288047484494474


(응용) 다차원의 배열을 1차원으로 평면화 하는 flatten 함수로 응용해보겠습니다.

- `np.flatten()`
- 3차원의 배열을 -> 1차원으로 평면화 하고 -> 최대값을 10으로 변경해주세요

`flat()` 함수는 다차원 배열을 1차원으로 평면화하는 간편한 방법을 제공합니다. 이를 통해 다차원 배열의 요소에 순차적으로 접근하거나, 1차원 배열로 변환하여 다양한 연산에 활용할 수 있습니다.

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6], [3, 4, 5]])

arr_f = arr.flat # 다차원 배열을 1차원으로 평면화

arr_f[arr.argmax()] = 10 # 최대값을 갖는 인덱스의 값을 10으로 변경

# 평면화된 1차원 배열의 요소에 접근 가능하므로, 최대값을 갖는 인덱스에 접근하여 값 변경도 가능

print(arr) # 원본 다차원 배열 arr에도 해당 변경이 반영됨 

[[ 1  2  3]
 [ 4  5 10]
 [ 3  4  5]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [3, 4, 5]])

arr_f = arr.flatten() 
arr_f[arr.argmax()] = 10 

print(arr_f)
print(arr)

[ 1  2  3  4  5 10  3  4  5]
[[1 2 3]
 [4 5 6]
 [3 4 5]]


(응용) 4차원(3,4,3,4)으로 주어진 범위(0,10) 안에서 정수형 변수를 생성해주세요
- 마지막 2축(axis)에서 합계를 출력해보세요

In [ ]:
z = np.random.randint(0, 10, size=(3, 4, 3, 4))
s = z.sum(axis = (-2,-1))
# print(z)
print(s)

[[45 66 56 58]
 [65 38 47 57]
 [49 42 62 54]]


배열의 첫번째 행과 두번째행을 바꾸어 봅시다

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## arg 인덱스 접근 함수 추가

(응용) 표준정규분포를 사용해서 100개의 난수를 생성해주세요.

그 후 `shuffle()` 함수를 사용해서 순서를 섞어줍니다.

`sort()` 함수와 마찬가지로 `argsort()` 를 이용해 인덱스를 사용합니다

- `argsort()` 를 사용해서 가장 큰 값을 5개만 뽑아봅시다.

In [ ]:
z = np.random.randn(100) # np.random.normal(0, 1, 100)

np.random.shuffle(z)

m5 = z[np.argsort(z)[-5:]]
print(m5)

[1.69326298 1.77644571 1.89470911 2.32229711 2.35836663]


배열의 인덱스에 접근하기 위해 사용할 수 있는 함수

> `np.argmax()`: 배열에서 최댓값의 인덱스를 반환합니다.

> `np.argmin()`: 배열에서 최솟값의 인덱스를 반환합니다.

> `np.argwhere()`: 조건을 충족하는 요소의 인덱스를 반환합니다. 반환되는 값은 2차원 배열이며, 각 행은 해당 요소의 인덱스를 나타냅니다.

> `np.where()`: 조건에 따라 요소를 선택하고, 선택된 요소의 인덱스를 반환합니다.

> `np.nonzero()`: 0이 아닌 요소의 인덱스를 반환합니다. 반환되는 값은 각 차원별로 분리된 인덱스 배열입니다.

In [19]:
arr = np.array([1, 3, 2, 5, 4])

# 최댓값의 인덱스
max_index = np.argmax(arr)
print("Max index:", max_index)  

# 최솟값의 인덱스
min_index = np.argmin(arr)
print("Min index:", min_index)  

# 조건을 충족하는 요소의 인덱스
index = np.argwhere(arr > 2)
print("Indices greater than 2:", index)  # 반환값 2차원 [[1] [3] [4]]

# 조건에 따라 요소 선택 및 인덱스 반환
selected_index = np.where(arr > 2)
print("Selected indices:", selected_index)  

# 0이 아닌 요소의 인덱스
nonzero_index = np.nonzero(arr)
print("Nonzero indices:", nonzero_index)  

Max index: 3
Min index: 0
Indices greater than 2: [[1]
 [3]
 [4]]
Selected indices: (array([1, 3, 4]),)
Nonzero indices: (array([0, 1, 2, 3, 4]),)
