<a href="https://colab.research.google.com/github/yesyell/DA_School_1/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%20%ED%95%B8%EB%93%A4%EB%A7%81/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EC%8A%A4%EC%BF%A8_0523.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

**브로드 캐스팅**
- 두 배열의 차원의 크기가 같다 -> 그냥 계산
- 두 배열의 차원의 크기가 다르고 한 배열의 차원이 1차원(벡터)
- 차원을 늘렸을 때 계산이 가능한 경우!

## 난수 생성 함수 - Random

In [ ]:
import numpy as np

In [ ]:
a = np.random.rand(2, 2)  # rand : 0 ~ 1 사이 값 랜덤 
print(a)

[[0.07409715 0.99721913]
 [0.02332944 0.31765626]]


In [ ]:
b = np.random.randn(2, 2)  # randn : 평균=0, 분산=1 : 표준 정규 분포 
print(b)

[[-0.08187103  1.51894291]
 [ 0.74487199 -2.26301044]]


In [ ]:
c = np.random.randint(0, 10, size=5)  # 랜덤한 정수값 생성 : 0 ~ 9의 5개의 값 
print(c)

[7 5 8 4 7]


In [ ]:
c2 = np.random.randint(0, 10, size=(2, 2))
print(c2)

[[8 6]
 [4 6]]


In [ ]:
d = np.arange(10) # 0 ~ 9 까지 값 생성 
print(d)
np.random.shuffle(d) # shuffle : 복사본 생성 x -> 원본 값이 변경됨 
print(d)

[0 1 2 3 4 5 6 7 8 9]
[7 2 3 6 4 0 5 9 1 8]


In [ ]:
# choice = np.random.choice(d, 5) # 중복 허용 
choice = np.random.choice(d, 5, replace=False) # 중복 허용 x
print(choice)

[1 0 2 4 3]


In [ ]:
d = np.arange(5)
choice = np.random.choice(d, 5, 
                          p=[0.1, 0.3, 0.2, 0.3, 0.1]) # p값을 100%(1)로 설정 
print(choice)

[4 4 3 1 1]


In [ ]:
# permutation 순열 : 서로 다른 n개의 원소에서 r개를 중복없이 순서에 상관있게 선택 혹은 나열하는 것
a = np.arange(10)
a_p = np.random.permutation(a)
print(a_p)
print(a)  # 원본 값이 유지됨 

[4 2 3 7 5 8 6 9 0 1]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 정규분포를 따르는 난수 생성
# a = np.random.normal('평균', '표준편차', '갯수')
a = np.random.normal(0, 1, 3)  # == np.random.randn(3)
print(a)

[ 0.66192764  0.57044938 -1.11499736]


# Pandas

- 데이터 자체를 분석, 파악
- 표, 테이블
- 데이터 다루는 데 초점
- 정렬, 필터링, 그룹화, 집계


---
기능 
1. 데이터 로딩 및 저장
2. 데이터 인덱싱 및 슬라이싱
3. 결측치 처리
4. 데이터 변환
5. 데이터 집계 및 그룹화
6. 시계열 데이터
7. 데이터 시각화
---
구조
1. Series (시리즈)
2. DataFrame (데이터프레임)


## Series (시리즈)

- 인덱스를 지정할 수 있음


In [ ]:
import pandas as pd

In [ ]:
# List로 생성하기 
s = pd.Series([1, 2, 3, 4])
print(s)

0    1
1    2
2    3
3    4
dtype: int64


In [ ]:
# Dictionary로 생성하기 
s2 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})
print(s2)

a    1
b    2
c    3
d    4
dtype: int64


In [ ]:
# Scalar 값으로 생성하기 
s3 = pd.Series(5, index=[0, 1, 2])
print(s3)

0    5
1    5
2    5
dtype: int64


### 인덱싱/슬라이싱 

**명시적 인덱스(Explicit Index)** : 사용자가 직접 지정한 인덱스

- 인덱스를 임의로 설정할 수 있으며, 이를 통해 데이터를 쉽게 조회할 수 있습니다.

**묵시적 인덱스(Implicit Index)** : 판다스가 자동으로 생성하는 인덱스

- 0부터 시작하는 정수형 인덱스로, 데이터프레임과 시리즈를 생성할 때 index 속성을 설정하지 않으면 자동으로 생성됩니다.

In [ ]:
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index) # 명시적 인덱스 
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
series = pd.Series(data) # 묵시적 인덱스 
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
# 슬라이싱 
print(series[0])
print(series[0:3])
print(series[::-1]) # 역순 
print(series) # 원본 유지 

1
0    1
1    2
2    3
dtype: int64
4    5
3    4
2    3
1    2
0    1
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64


### Boolean Indexing

In [ ]:
print(series > 2) # -> Bool 

print(series[series > 2]) # a[a 조건]

0    False
1    False
2     True
3     True
4     True
dtype: bool
2    3
3    4
4    5
dtype: int64


In [ ]:
# 5보다 작은 시리즈 만들기
print(series[series < 5])

0    1
1    2
2    3
3    4
dtype: int64


### 산술 연산 

In [ ]:
print(series + 100)
print(series - 100)
print(series * 100) # 곱 
print(series ** 100) # 제곱 
print(series / 100) # 몫 (float)
print(series % 100) # 나머지 
print(series // 100) # 몫 (int)
# 원본 유지. 그저 계산 결과 

0    101
1    102
2    103
3    104
4    105
dtype: int64
0   -99
1   -98
2   -97
3   -96
4   -95
dtype: int64
0    100
1    200
2    300
3    400
4    500
dtype: int64
0                      1
1                      0
2   -2984622845537545263
3                      0
4   -3842938066129721103
dtype: int64
0    0.01
1    0.02
2    0.03
3    0.04
4    0.05
dtype: float64
0    1
1    2
2    3
3    4
4    5
dtype: int64
0    0
1    0
2    0
3    0
4    0
dtype: int64


### 객체 접근

- keys -> index
- values
- items


In [ ]:
series = pd.Series([1, 2, 3, 4, 5])
print(series.keys)

print(series.keys())
print(series.index)
# RangeIndex - Pandas에서 자동으로 인덱스를 생성해준 것 

print(series.values)

print(series[0])
print(series.values[0])

<bound method Series.keys of 0    1
1    2
2    3
3    4
4    5
dtype: int64>
RangeIndex(start=0, stop=5, step=1)
RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]
1
1


In [ ]:
s2 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})
print(s2.keys)

print(s2.keys()) # 메서드 호출 
print(s2.index)

<bound method Series.keys of a    1
b    2
c    3
d    4
dtype: int64>
Index(['a', 'b', 'c', 'd'], dtype='object')
Index(['a', 'b', 'c', 'd'], dtype='object')


In [ ]:
print(s2.items()) # zip : 순회 가능한 쌍 

for index, value in s2.items():
    print(f'인덱스: {index}, 데이터: {value}')

인덱스: a, 데이터: 1
인덱스: b, 데이터: 2
인덱스: c, 데이터: 3
인덱스: d, 데이터: 4


In [ ]:
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(s)

a    10
b    20
c    30
d    40
dtype: int64


In [ ]:
# loc : 행에 접근 
print(s.loc['a']) 
print(s.loc['b':'d']) # 레이블 지정 -> 'd' 포함 
# print(s['a']) 
# print(s['b':'d'])

# iloc :(행에 기반한) 열에 접근
print(s.iloc[1])
print(s.iloc[1:3]) # 일반 슬라이싱과 동일 -> 3 미포함 

10
b    20
c    30
d    40
dtype: int64
20
b    20
c    30
dtype: int64


위의 코드에서 `s['b':'d']`와 `s.loc['b':'d']` 모두 'b'부터 'd'까지의 값을 선택하여 동일한 결과를 반환합니다.

이러한 이유는 pandas가 일반적인 경우에는 인덱스 레이블을 기반으로 슬라이싱을 수행하기 때문입니다. 따라서, 일반적인 정수 인덱스가 아닌 인덱스 레이블을 가진 경우에도 `s['b':'d']`를 사용하여 슬라이싱을 수행할 수 있습니다.

하지만 차이점은 존재합니다. loc을 사용하면 인덱스 레이블을 명시적으로 사용하여 데이터에 접근하는 것이므로, 인덱스 레이블의 타입에 따라 조금 다른 동작을 할 수 있습니다. 또한, loc을 사용하여 단일 인덱스 레이블을 선택하는 것과 슬라이싱을 통해 데이터에 접근하는 것은 일관성을 유지하기 위해 구문적으로 구분될 수 있습니다.

따라서, `s['b':'d']`와 `s.loc['b':'d']`는 대부분의 경우 동일한 결과를 제공하지만, loc은 더 많은 유연성을 제공하고 명시적인 인덱스 레이블 기반의 데이터 접근 방법을 제공합니다.

In [ ]:
# at : loc 과 비슷, 하나의 값만 가져올 때
print(s.at['a'])

# iat : iloc 과 비슷 
print(s.iat[1])

10
20


In [ ]:
# get : 없는 값에 대한 처리 방식 다름 -> error 대신 default
print(s.get('e', default=-1))

-1


### 결측값 (Nan, None)

- Nan(Not a Number) -> float
- None -> none
    - isna() = isnull()
    - notna() = notnull()
        - sum() 으로 카운팅 
    - dropna()
    - fillna(num)

In [ ]:
import numpy as np
import pandas as pd

data = [1, 2, 3, None] # list

print(np.array(data)) # None - 수치연산 시 error
print()
print(pd.Series(data)) # NaN - 수치연산 처리가 용이

[1 2 3 None]

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64


In [ ]:
s = pd.Series([1, 2, 3, None])

print(s.isna())
# print(s.isnull())

print(s.isna().sum()) # True 값 카운팅 
# print(s.isnull().sum())

print(s.notnull())

0    False
1    False
2    False
3     True
dtype: bool
1
0     True
1     True
2     True
3    False
dtype: bool


In [ ]:
# 결측치 제거
print(s.dropna())

# 결측치를 0으로 치환 
print(s.fillna(0))

0    1.0
1    2.0
2    3.0
dtype: float64
0    1.0
1    2.0
2    3.0
3    0.0
dtype: float64


### 집계함수

In [ ]:
s = pd.Series([1, 3, 5, 7, 9])

print(s.count()) # 카운트 함수 
print(s.min()) # 최소값
print(s.max()) # 최대값 

print(s.mean()) # 평균 
print(s.median()) # 중앙값  
print(s.std()) # 표준편차 
print(s.var()) # 분산 

5
1
9
5.0
5.0
3.1622776601683795
10.0


In [ ]:
print(s.describe()) # 기초 통계를 한 번에 볼 수 있는 함수

count    5.000000
mean     5.000000
std      3.162278
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
dtype: float64
