<a href="https://colab.research.google.com/github/yesyell/DA_School_1/blob/main/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98%2C%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0/python100%EC%A0%9C_1to100.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Python 100제 - 1권](https://pythonworkbook.notion.site/Python-100-1-abeccbfd8175483da1ed96642640c687)

# 1번

In [ ]:
nums = [100, 200, 300, 400, 500]
nums.pop()
nums.pop()
nums

[100, 200, 300]

In [ ]:
nums = [100, 200, 300, 400, 500]
nums[:3]

[100, 200, 300]

In [ ]:
nums = [100, 200, 300, 400, 500]
nums[-5:-2]

[100, 200, 300]

# 2번

In [ ]:
l = [200, 100, 300]
l.insert(2, 10000)
l

[200, 100, 10000, 300]

In [ ]:
l = [200, 100, 300]
l[:2] + [10000] + [l[-1]]
# l[:2] + [10000] + l[-1] # error

[200, 100, 10000, 300]

# 3번

In [ ]:
l = [100, 200, 300]
print(type(l))

<class 'list'>


# 4번

In [ ]:
# 1)  입력 : a 4= 1,   출력 : class 'int'
# 2)  입력 : a = 2.22,   출력 : class 'float'
## 3)  입력 : a = 'p',   출력 : class 'char' -> 'str'
# 4)  입력 : a = [1, 2, 3],   출력 : class 'list'

#5번

In [ ]:
a = 10
b = 2
for i in range(1, 5, 2):
    a += i
print(a+b)

16


# 6번

In [ ]:
# 다음은 파이썬 문법 중에서 False로 취급하는 것들 입니다.
# False로 취급하지 않는 것이 하나 있네요! **True를 찾아주세요.**

# 1)  None
## 2)  1
# 3)  ""
# 4)  0
# 5)  bool(0)

In [ ]:
print(bool([]))
print(bool([1, 2, 3]))

False
True


In [ ]:
l = []
print(id(l))
print(bool(l))

135131996370496
False


In [ ]:
l.append(10)
print(id(l))
print(bool(l))

135131996370496
True


In [ ]:
# l 값은 변하지 않지만 bool 값은 변함
# python은 지극히 인간의 입장에서 출력을 고려한 것임

# 7번

In [ ]:
# 다음 중 변수명으로 사용할 수 없는 것 2개를 고르시오.
# 1)  age
# 2)  a
## 3)  as
# 4)  _age
## 5)  1age

In [ ]:
# 반복문 등에서 사용하지 않는 변수에 _를 넣습니다.
for _ in range(5):
    print('hello')

hello
hello
hello
hello
hello


In [ ]:
# 프라이빗한 변수에 _를 사용합니다.
class Human():
    _age = 0

# 8번

In [ ]:
d = {'height':180,
     'weight':78,
     'weight':84,
     'temparture':36,
     'eyesight':1}
print(d['weight'])

84


# 9번

In [ ]:
year = '2019'
month = '04'
day = '26'
hour = '11'
minute = '34'
second = '27'

print(year, month, day, sep='/', end=' ')
print(hour, minute, second, sep=':')
# 2019/04/26 11:34:27

2019/04/26 11:34:27


# 10번

In [ ]:
n = int(input())
for i in range(1, n+1):
    print(' ' * (n-i) + '*' * (i*2-1))

#     *
#    ***
#   *****
#  *******
# *********

5
    *
   ***
  *****
 *******
*********


# 11번

In [ ]:
s = 0
for i in range(1, 101):
    s += i
print(s)

5050


# 12번

In [ ]:
class Wizard():
    def __init__(self, health, mana, armor):
        # self는 인스턴스, 인스턴스 메모리 영역
        self.health = health
        self.mana = mana
        self.armor = armor
    def attack(self):
        print('파이어볼')

jik = Wizard(health = 545, mana = 210, armor = 10)
print(jik.health, jik.mana, jik.armor)
jik.attack()
# 545 210 10
# 파이어볼

545 210 10
파이어볼


# 13번

In [ ]:
# 태양계의 n번째 행성
planets = ['수성', '금성', '지구', '화성', '목성', '토성', '천왕성', '해왕성']

n = int(input())
print(planets[n-1])

3
지구


# 14번

In [ ]:
# 만약 그 수가 3의 배수라면 '짝'이라는 글자를, 3의 배수가 아니라면 n을 그대로 출력해 주세요.
n = int(input())

if n % 3 == 0:
    print('짝')
else:
    print('홀')

6
짝


[저주의 숫자3](https://school.programmers.co.kr/learn/courses/30/lessons/120871)

In [ ]:
# 소거법
[i for i in range(100) if i%3 != 0] # 3의 배수 제거
[i for i in range(100) if '3' not in str(i)] # 3이 들어가 있는 숫자 제거

n = 10
[i for i in range(100) if i%3 != 0 and '3' not in str(i)][n-1]

16

In [ ]:
solution = lambda n:[i for i in range(10000) if i % 3 != 0 and '3' not in str(i)][n-1]
solution(10)

16

In [ ]:
def solution(n):
    return list(filter(lambda x: '3' not in str(x),
                filter(lambda x: x%3 != 0, range(1000))))[n-1]

solution(15)

25

# 15번

In [ ]:
# 안녕하세요. 저는 김다정입니다.

# 16번

In [ ]:
# 거꾸로 출력
'안녕하세요'[::-1]

'요세하녕안'

In [ ]:
''.join(list(reversed(list('안녕하세요'))))

'요세하녕안'

In [ ]:
s = '안녕하세요'
ss = list(s)
ss.reverse()
''.join(ss)

'요세하녕안'

In [ ]:
s = '안녕하세요'
result = ''
for i in s:
    result = i + result
result

'요세하녕안'

In [ ]:
# 재귀
def reverse(s):
    if len(s) == 1:
        return s
    else:
        return reverse(s[1:]) + s[0]
reverse('안녕하세요')

'요세하녕안'

# 17번

In [ ]:
# 입력으로 키가 주어지면 키가 150이 이상이면 YES를 틀리면 NO를 출력하는 프로그램
height = int(input())

# print('NO') if height >= 150: print('YES') # Error
print('YES') if height >= 150 else print('NO')

149
NO


In [ ]:
def solution(height):
    return 'YES' if height >= 150 else 'NO'
solution(150)

'YES'

# 18번

In [ ]:
# 공백으로 구분하여 세 과목의 점수가 주어지면, 전체 평균 점수를 구하는 프로그램
# 단, 소숫점 자리는 모두 버립니다.

list(map(int, '20 30 40'.split(' ')))

[20, 30, 40]

In [ ]:
score = input()
sum(map(int, score.split(' '))) // 3

20 30 40


30

# 19번

In [ ]:
# 공백으로 구분하여 두 숫자 a와 b가 주어지면, a의 b승을 구하는 프로그램
n = input()
l = list(map(int, n.split(' ')))
l[0] ** l[1]

2 4


16

# 20번

In [ ]:
# 공백으로 구분하여 두 숫자가 주어집니다.
# 첫번째 숫자로 두번째 숫자를 나누었을 때 그 몫과 나머지를 공백으로 구분하여 출력하세요.
n = input()
l = list(map(int, n.split(' ')))
print(l[0]//l[1], l[0]%l[1], sep=' ')

17 3
5 2


# 21번

In [ ]:
# 다음 중 set을 만드는 방법이 아닌 것?
# 1)  x = {1, 2, 3, 5, 6, 7}
## 2)  x = {} -> dict
# 3)  x = set('python')
# 4)  x = set(range(5))
# 5)  x = set()

In [ ]:
t = 1
t = (1) # tuple 아님
t = (1,)
t

(1,)

In [ ]:
# 어떤 라이브러리나 프레임워크 마지막 콤마가 꼭 있는 이유 :
# 버전 관리하는 곳에서 콤마를 버전의 업이라고 인식하는 경우가 있음
# 튜플의 경우 상수, 문자가 들어갔을 때 튜플이 아닌 int, str로 변환되는 것을 막기 위해

# 22번

In [ ]:
# 다음 중 변수 i가 6의 배수인지 확인하는 방법으로 올바른 것은?
# 1)  i / 6 == 0
## 2)  i % 6 == 0
# 3)  i & 6 == 0
# 4)  i | 6 == 0
# 5)  i // 6 == 0

# 23번

In [ ]:
# print(10/2)의 출력 결과는 5이다. (X)
(10/2)

5.0

# 24번

In [ ]:
'mary'.upper()

'MARY'

In [ ]:
ord('a')

97

In [ ]:
ord('A')

65

In [ ]:
ord('a') - ord('A') # 대소문자 차이 32로 일정

32

In [ ]:
chr(ord('a') - 32)

'A'

In [ ]:
for i in 'mary':
    print(chr(ord(i)-32), end='')
# 완벽한 코드는 아니고, 소문자인 것을 판단하는 if가 위에 있어야 합니다.

MARY

# 25번

In [ ]:
# 입력을 반지름의 길이로 정수 n이 주어지면 원의 넓이를 반환하는 함수를 만들어 주세요.
n = 3
print(n**2*3.14)

28.26


# 26번

In [ ]:
key = '수성, 금성, 지구, 화성, 목성, 토성, 천왕성, 해왕성'.split(', ')
value = 'Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune'.split(', ')

In [ ]:
dict(zip(key, value))

{'수성': 'Mercury',
 '금성': 'Venus',
 '지구': 'Earth',
 '화성': 'Mars',
 '목성': 'Jupiter',
 '토성': 'Saturn',
 '천왕성': 'Uranus',
 '해왕성': 'Neptune'}

# 27번

In [ ]:
# 두 개를 합쳐 학생의 이름이 key이고 value가 수학 점수인 딕셔너리를 출력해주세요.

# 28번

In [ ]:
# 2-gram
s = 'Python'
for i in range(len(s)-1):
    print(s[i:i+2])

Py
yt
th
ho
on


In [ ]:
list(zip(s, s[1:])) # 짝이 안맞으면 어차피 생성하지 않음

[('P', 'y'), ('y', 't'), ('t', 'h'), ('h', 'o'), ('o', 'n')]

In [ ]:
for i in zip(s, s[1:]):
    print(''.join(i))

Py
yt
th
ho
on


In [ ]:
p = [1, 3, 5, 7, 11, 14, 19, 21, 22]
list(zip(p, p[1:]))

[(1, 3), (3, 5), (5, 7), (7, 11), (11, 14), (14, 19), (19, 21), (21, 22)]

In [ ]:
list(map(lambda x: x[1]-x[0], zip(p, p[1:])))

[2, 2, 2, 4, 3, 5, 2, 1]

# 29번

In [ ]:
# 알파벳 하나만을 입력하고 그 알파벳이 대문자이면 YES를 아니면 NO를 출력하는 프로그램


In [ ]:
# 알파벳 여러개를 입력하고 여러개 입력한 것 중 대문자만 출력해주는 프로그램
# 'HellO WoRld' -> HOWR

for s in 'HellO WoRld':
    if s.isupper(): # 코드의 의도가 가장 명확함
        print(s)

H
O
W
R


In [ ]:
for s in 'HellO WoRld':
    if s != s.lower():
        print(s)

H
O
W
R


In [ ]:
for s in 'HellO WoRld':
    if 'A' <= s <= 'Z':
        print(s)

H
O
W
R


# 30번

In [ ]:
# 입력으로 첫 줄에 문자열이 주어지고 둘째 줄에 찾을 문자가 주어지면 그 문자가 시작하는 index를 반환하는 프로그램

'pineapple is yummy'.find('apple') # 없으면 -1
'pineapple is yummy'.index('apple') # 없으면 error

# 예를 들어 주기적으로 크롤링하는 코드가 있다면
# find를 쓰셔서 error가 안나고 다음 코드로 넘어가게 코딩하실 수 있습니다.
# 예외처리를 하는 것이 가장 좋습니다.
# 정답: 목적에 맞게 사용하셔야 합니다.

4

In [ ]:
'pineapple is yummy apple'.find('apple')
'pineapple is yummy apple'.index('apple')

4

In [ ]:
'pineapple is yummy apple'.rfind('apple')
'pineapple is yummy apple'.rindex('apple')

19

In [ ]:
'pineapple is yummy apple'.find('apple', 10)
'pineapple is yummy apple'.index('apple', 10)

19

# 31번

[파이썬 자료형의 복잡도](https://wayhome25.github.io/python/2017/06/14/time-complexity/)

In [ ]:
# 다음 리스트의 내장함수의 시간 복잡도가 O(1)이 아닌것은?
# 1)  l[i]
# 2)  l.append(5)
## 3)  l[a:b] -> O(b-a)
# 4)  l.pop()
# 5)  l.clear()

In [ ]:
# slice 사용 경우 -> error 발생시키지 않기 위해
l = [1, 2, 3, 4, 5]

# l[10]  # out of range error
l[10:11] # out of range error가 안나지만 기능은 같음

[]

# 32번

In [ ]:
# 문자열을 입력받으면 단어의 갯수를 출력하는 프로그램
s = input()
len(s.split(' '))

My name is yelin.


4

# 33번

In [ ]:
# 한 줄에 여러개의 숫자가 입력되면, 역순으로 그 숫자들을 하나씩 출력하는 프로그램
n = input()
list(map(int, n.split()))[::-1]

3 6 2 8 1 7


[7, 1, 8, 2, 6, 3]

# 34번

In [ ]:
# sort 확인
# 키가 주어지면 순서대로 제대로 섰는지 확인하는 프로그램

# 35번 ** 중요 **

In [ ]:
# 2제곱, 3제곱, 4제곱을 할 수 있는 Factory 함수
def one(n):
    def two(value):
        return value**n
    return two

a = one(2)
b = one(3)
c = one(4)
print(a(10))
print(b(10))
print(c(10))

100
1000
10000


In [ ]:
# id, name, email이 각각 3번씩 반복
# 이러한 현상을 보일러 플레이트(boiler-plate)라 함
# print를 해도 필드값이 보이지 않아 불편
class User:
    def __init__(self, id, name, email):
        self.id = id
        self.name = name
        self.email = email

    def __repr__(self):
        return (f'{self.__class__.__qualname__}{self.id, self.name, self.email}')

user = User(123, 'hojun', 'hojun@gmail')
user

User(123, 'hojun', 'hojun@gmail')

In [ ]:
from dataclasses import dataclass

@dataclass
class User:
    id: int
    name: str
    email : str

user = User(123, 'hojun', 'hojun@gmail')
user

User(id=123, name='hojun', email='hojun@gmail')

In [ ]:
# 객체지향 프로그래밍 예제
class Book:
    def __init__(self, title, content, author, pub_date):
        self.title = title
        self.content = content
        self.author = author
        self.pub_date = pub_date

    def calculate_date(self):
         self.pub_date - self.current_date

In [ ]:
# 1. 함수를 변수에 할당할 수 있습니다.
# 2. 함수를 데이터 구조에 저장할 수 있습니다.
# 3. 함수를 인자로 다른 함수에 전달할 수 있습니다.
# 4. 함수를 결과로서 반환할 수 있습니다.

In [ ]:
def add(x, y):
    return x+y
x = add
x(10, 20)

30

In [ ]:
id(x), id(add)

(139626571079904, 139626571079904)

In [ ]:
test = [x, add]
test[0](10, 20)

30

In [ ]:
def add():
    return lambda x: x**2
x = add()
x(10)

100

In [ ]:
def add():
    return lambda x: x**2
add()(10)

100

In [ ]:
def add(x, y):
    def test(x):
        return x*2
    test(x)
    return 'hello'
add(10, 20)

'hello'

In [ ]:
def sub(x, y):
    return x - y
def add(x, y, f):
    def test(x):
        return x * 2
    test(x)
    return 'hello'

add(10, 20, sub) # call back 함수

# map(int, ['1', '2']) # int를 콜백 함수라고도 부름

'hello'

## 데코레이터

In [ ]:
def simple_decorator(function):
    def wrapper():
        print("Before the function call")
        function()
        print("After the function call")
    return wrapper

@simple_decorator
def hello():
    print("Hello, World!")

hello() # 데코레이터가 없는 상태에서는 simple_decorator(hello)() 와 같습니다.

Before the function call
Hello, World!
After the function call


In [ ]:
def simple_decorator(function):
    def wrapper(l):
        print("Before the function call")
        print(function(map(int, l)))
        print("After the function call")
    return wrapper

@simple_decorator
def 합(l):
    return sum(l)

합([1, 2, 3, '4'])

Before the function call
10
After the function call


In [ ]:
def debug(function):
    def new_function(*args):
        print(f'{function.__name__} 함수 시작')
        print(*args)
        result = function(*args)
        print(f'{function.__name__} 함수 끝')
        # return result # return 값이 있는 데코레이터는 바로 뒤에서 진행합니다.

    return new_function

@debug
def sum_1_to_n(n):
    return n * (n + 1) / 2

result = sum_1_to_n(30)

print(result)

sum_1_to_n 함수 시작
30
sum_1_to_n 함수 끝
None


In [ ]:
def test(*args):
    for i in args:
        print(i)

test(1, 2, 3, 4, 5, 'hello world')

1
2
3
4
5
hello world


In [ ]:
def test(**kargs):
    print(kargs)
    for i in kargs:
        print(i)

test(one=1, two=2, three=3)

{'one': 1, 'two': 2, 'three': 3}
one
two
three


In [ ]:
def decorator1(function):
    def new_function(*args, **kwargs):
        print('첫번째 데코레이터 시작')
        result = function(*args, **kwargs)
        print('첫번째 데코레이터 끝')
        return result
    return new_function

def decorator2(function):
    def new_function(*args, **kwargs):
        print('두번째 데코레이터 시작')
        result = function(*args, **kwargs)
        print('두번째 데코레이터 끝')
        return result
    return new_function

def decorator3(function):
    def new_function(*args, **kwargs):
        print('세번째 데코레이터 시작')
        result = function(*args, **kwargs)
        print('세번째 데코레이터 끝')
        return result
    return new_function

@decorator1
@decorator2
@decorator3
def sum_1_to_n(n):
    return n * (n + 1) / 2

result = sum_1_to_n(30)

print(f'result: {result}')

첫번째 데코레이터 시작
두번째 데코레이터 시작
세번째 데코레이터 시작
세번째 데코레이터 끝
두번째 데코레이터 끝
첫번째 데코레이터 끝
result: 465.0


In [ ]:
def add(n):
    def decorator(function):
        def new_function(*args, **kwargs):
            result = function(*args, **kwargs)
            return result + n
        return new_function
    return decorator

@add(10)
def plus(a, b):
    return a + b

result = plus(10, 20)
print(f'result : {result}')

result : 40


# 36번

In [ ]:
n = 2
for i in range(1, 10):
    print(n*i, end=' ')

2 4 6 8 10 12 14 16 18 

In [ ]:
# 1부터 10000까지 8이라는 숫자를 count하라
str(list(range(10000))).count('8')

4000

# 37번

In [ ]:
# 입력 : 원범 원범 혜원 혜원 혜원 혜원 유진 유진
# 출력 : 혜원(이)가 총 4표로 반장이 되었습니다.

# 38번

In [ ]:
l = set(map(int, '97 86 75 66 55 97 85 97 97 95'.split(' ')))
sorted(l, reverse=True)[:3]

[97, 95, 86]

In [ ]:
list(reversed(sorted(set(map(int, '97 86 75 66 55 97 85 97 97 95'.split(' '))))))[:3]

[97, 95, 86]

In [ ]:
# 1자리 점수가 등수에 들어갔을 때는 오류가 남
def solution(s):
    answer = 0
    splitdata = map(int, s.split(' '))
    for i in list(reversed(sorted(set(splitdata))))[:3]:
        answer += s.count(str(i))
    return answer
solution('97 86 75 66 55 97 85 97 97 95')

6

In [ ]:
# map으로 된 데이터가 왜 한 번만 순회가 되었는지
# https://www.notion.so/paullabworkspace/python-zip-b7a1992be7884891a5f1d0a5c0c2df9c?pvs=4

def solution(s):
    answer = 0
    # splitdata = map(int, s.split(' '))
    splitdata = list(map(int, s.split(' ')))
    for i in list(reversed(sorted(set(splitdata))))[:3]:
        for j in splitdata:
            if i == j:
                answer += 1
    return answer
solution('97 86 75 66 55 97 85 97 97 95')

6

In [ ]:
import collections

collections.Counter('97 86 75 66 55 97 85 97 97 95'.split(' '))

Counter({'97': 4, '86': 1, '75': 1, '66': 1, '55': 1, '85': 1, '95': 1})

In [ ]:
data = input().split()
data = [int(i) for i in data]
count = 0

if len(set(data)) <= 3:
    count = len(data)
else:
    break_point = sorted(list(set(data)), reverse=True)[3]
    data_sorted = sorted(data, reverse=True)
    for i in data_sorted:
        if break_point == i:
            break
        else:
            count += 1

print(count)

97 86 75 66 55 97 85 97 97 95
6


# 39번

In [ ]:
# 문장이 입력되면 모든 q를 e로, b를 n으로 바꾸는 프로그램

'querty'.replace('q', 'e').replace('b', 'n')

'euerty'

In [ ]:
# https://github.com/paullabkorea/Algorithm-walk-with-wenivs/blob/main/3.%20pyalgo%20%ED%92%80%EC%9D%B4/%EC%A0%95%EA%B7%9C%ED%91%9C%ED%98%84%EC%8B%9D.ipynb
import re

result = re.sub('q', 'e', 'querbty')
result = re.sub('b', 'n', result)
result

'euernty'

# 40번

In [ ]:
# 첫번째 줄에서 제한 무게가 주어지고 두번째 줄에서는 함께한 친구들의 수 n이 주어집니다.
# 그 다음 차례대로 탑승할 친구들의 몸무게가 주어집니다. 몸무게는 무작위로 주어집니다.

# 41번

In [ ]:
# 숫자가 주어지면 소수인지 아닌지 판별하는 프로그램
# 소수이면 YES로, 소수가 아니면 NO로 출력
# 소수 : 1과 자기 자신만으로 나누어떨어지는 1보다 큰 양의 정수
# 음의 소수는 고려하지 않습니다.

In [ ]:
def prime_list(n):
    # 에라토스테네스의 체 초기화: n개 요소에 True 설정(소수로 간주)
    sieve = [True] * n

    # n의 최대 약수가 sqrt(n) 이하이므로 i=sqrt(n)까지 검사
    m = int(n ** 0.5)
    for i in range(2, m + 1):
        if sieve[i] == True:           # i가 소수인 경우
            for j in range(i+i, n, i): # i이후 i의 배수들을 False 판정
                sieve[j] = False
    print(sieve) # 0부터 시작해서 i가 소수인경우 True
    # 소수 목록 산출
    return [i for i in range(2, n) if sieve[i] == True]
prime_list(100)

[True, True, True, True, False, True, False, True, False, False, False, True, False, True, False, False, False, True, False, True, False, False, False, True, False, False, False, False, False, True, False, True, False, False, False, False, False, True, False, False, False, True, False, True, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, True, False, True, False, False, False, False, False, True, False, False, False, True, False, True, False, False, False, False, False, True, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, True, False, False]


[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

# 42번

In [ ]:
# 두 수 a, b를 입력받아 2020년 a월 b일이 무슨 요일인지 리턴하는 함수
import datetime

date = datetime.datetime.today()
date

datetime.datetime(2023, 8, 10, 2, 9, 18, 855642)

In [ ]:
date.year, date.month, date.day

(2023, 8, 10)

In [ ]:
datetime.date(2023, 8, 10).weekday()

3

# 43번

In [ ]:
# 사용자에게 숫자를 입력받고 이를 2진수를 바꾸고 그 값을 출력해주세요.
# (bin 함수를 사용하지 않고 풀어주세요.)

In [ ]:
bin(11)[2:]

'1011'

In [ ]:
# 음수 변환까지 하려면 좀 더 고려를 해야함
x = 11
s = ''
while x:
    print(x)
    s += str(x % 2)
    x = x // 2
s[::-1]

# 2 | 11 ... 1
#    ---
# 2 |  5 ... 1
#    ---
# 2 |  2 ... 0
#    ---
# 2 |  1

11
5
2
1


'1011'

# 44번

In [ ]:
# 사용자가 입력한 양의 정수의 각 자리수의 합을 구하는 프로그램
n = 1234
answer = 0
for i in str(n):
    answer += int(i)
answer

10

In [ ]:
n = 1234
sum(map(int, list(str(n))))

10

# 45번

# 46번

# 47번

In [ ]:
people = [('이호준', '01050442903'),
          ('이호상', '01051442904'),
          ('이준호', '01050342904'),
          ('이호준', '01050442903'),
          ('이준', '01050412904'),
          ('이호', '01050443904'),
          ('이호준', '01050442903'),]
len(set(people))

5

# 48번

In [ ]:
answer = ''
for i in 'AAABBBcccddd':
    if i.islower():
        answer += i.upper()
    else:
        answer += i.lower()
answer

'aaabbbCCCDDD'

# 49번

In [ ]:
# 최대값

# 50번

In [ ]:
# 버블정렬
def bubble(n, data):
	for i in range(n-1):
		for j in range(빈칸을 채워주세요):
			if data[j] > data[j+1]:
				빈칸을 채워주세요
	for i in range(n):
		print(data[i], end = " ")

n = int(input())
data = list(map(int, input().split()))

bubble(n, data)

# 51번

In [ ]:
#병합 정렬
def merge(입력리스트):
    입력리스트길이 = len(입력리스트)
    if 입력리스트길이 <= 1:
        return 입력리스트
    중간값 = 입력리스트길이 // 2
    그룹_하나 = merge(입력리스트[:중간값])
    그룹_둘 = merge(입력리스트[중간값:])
    결과값 = []

    while (#빈칸을 채워주세요) and (#빈칸을 채워주세요) :
        if (#빈칸을 채워주세요):
            결과값.append(그룹_하나.pop(0))
        else:
            결과값.append(그룹_둘.pop(0))

    while 그룹_하나:
        결과값.append(그룹_하나.pop(0))
    while 그룹_둘:
        결과값.append(그룹_둘.pop(0))
    return 결과값

주어진리스트 = [180, 145, 165, 45, 170, 175, 173, 171]
#빈칸을 채워주세요

print(merge(주어진리스트))

# 52번

In [ ]:
# quick
def quick(입력리스트):
    입력리스트의길이 = len(입력리스트)
    if 입력리스트의길이 <= 1:
        return 입력리스트
    기준값 = 입력리스트.pop(입력리스트의길이//2)
    그룹_하나 = []
    그룹_둘 = []

    for i in range(입력리스트의길이-1):
        if #내용을 채워주세요:
            그룹_하나.append(입력리스트[i])
        else:
            그룹_둘.append(입력리스트[i])
    return #내용을 채워주세요

주어진리스트 = input().split(' ')
#내용을 채워주세요.

print(quick(주어진리스트))

# 53번

In [ ]:
# 입력으로 주어진 괄호 문자열이 바른 문자열인지 바르지 않은 문자열인지 "YES"와 "NO"로 구분된 문자열을 출력해보자.
# '{', '}', '[', ']', '(', ')'
s = '()()'
brackets = []

if s.count('(') != s.count(')'):
    print(False)
else:
    for i in s:
        if i == ')' or i == '(':
            brackets.append(i)
    print(brackets)

['(', ')', '(', ')']


In [ ]:
s = '())()'
brackets = []

if s.count('(') != s.count(')'):
    print(False)
else:
    for i in s:
        if i == '(':
            brackets.append(i)
        elif i == ')':
            if len(brackets)==0:
                print(False)
            brackets.pop()
    print(True)

False


In [ ]:
def math(e):
    if e.count('(') != e.count(')'):
        return False
    괄호 = []
    for i in e:
        if i == '(':
            괄호.append('(')
        if i == ')':
            if len(괄호) == 0:
                return False
            괄호.pop()
    return True

n = input()
if math(n) == True:
	print("YES")
else:
	print("NO")

()())
NO


# 54번

In [ ]:
# 스탬프에 적힌 숫자가 공백으로 구분되어 주어지면 이 숫자가 연속수인지 아닌지 "YES"와 "NO"로 판별하는 프로그램
user_input = input().split(' ')
user_input = [int(i) for i in user_input]

def sol(l):
    l = sorted(l)
    for i in range(len(l) - 1):
        if l[i]+1 != l[i+1]:
            return 'NO'
    return 'YES'

print(sol(user_input))

1 2 3 5 4
YES


In [ ]:
value = list(map(int, '1 2 4 3 5'.split(' ')))
list(range(min(value), min(value) + len(value))) == sorted(value)

True

In [ ]:
def solution(num):
    num = num.split(' ')
    num = list(map(int, sorted(num)))
    for i in list(zip(num, num[1:])):
        if i[1] - i[0] != 1:
            return 'NO'
    return 'YES'

solution('1 4 2 5 3')

'YES'

# 55번 하노이

In [ ]:
# [[A, C], [A, B], [C, B], [A, C], [B, A], [B, C], [A, C]]
원판의이동경로 = []
def 하노이(원반의수, 시작기둥, 목표기둥, 보조기둥):
    # 원판이 한개일 때에는 옮기면 됩니다.
    if 원반의수 == 1:
        원판의이동경로.append([시작기둥, 목표기둥])
        return None
    # 원반의 n-1개를 경유기둥으로 옮기고
    하노이(원반의수-1, 시작기둥, 보조기둥, 목표기둥) # 여기가 문제였습니다.
    # 가장 큰 원반은 목표기둥으로
    원판의이동경로.append([시작기둥, 목표기둥])
    # 경유기둥과 시작기둥을 바꿉니다!
    하노이(원반의수-1, 보조기둥, 목표기둥, 시작기둥)

하노이(3,'A','C','B')

print(len(원판의이동경로))
원판의이동경로

7


[['A', 'C'],
 ['A', 'B'],
 ['C', 'B'],
 ['A', 'C'],
 ['B', 'A'],
 ['B', 'C'],
 ['A', 'C']]

# 56번

In [ ]:
nationWidth = {
    'korea': 220877,
    'Rusia': 17098242,
    'China': 9596961,
    'France': 543965,
    'Japan': 377915,
    'England': 242900,
    'A': 543965,
}

korea = nationWidth.pop('korea') # nationWidth['korea']
mini = float('inf')
result_key = ''

for key in nationWidth:
    value = nationWidth[key] - korea
    if value < mini:
        mini = value
        result_key = key

result_key, mini

('England', 22023)

In [ ]:
nationWidth = {
    'Rusia': 17098242,
    'China': 9596961,
    'France': 543965,
    'Japan': 377915,
    'England': 242900
}

def f(key):
    return [nationWidth[key] - 220877, key]

list(map(f, nationWidth))
min(map(f, nationWidth))

[22023, 'England']

In [ ]:
nationWidth = {
    'Rusia': 17098242,
    'China': 9596961,
    'France': 543965,
    'Japan': 377915,
    'England': 242900
}

min(map(lambda key: [nationWidth[key]-220877, key], nationWidth))[1]

'England'

# 57번

In [ ]:
# 0부터 1000까지 수에서 1은 몇번이나 들어갔을까요?

# 58번

In [ ]:
# 숫자를 입력 받고 천단위로 콤마(,)를 찍어주세요.

# 59번

In [ ]:
# 총 문자열의 길이는 50으로 제한하고 사용자가 문자열을 입력하면 그 문자열을 가운데 정렬을 해주고, 나머지 빈 부분에는 '='을 채워넣어주세요

s = 'hi'
print(f'{s:=^50}')
print(f'{s:!<50}')
print(f'{s:~>50}')

========================hi========================
hi!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~hi


In [ ]:
s = 'hello world'
print(('='*(((50//2)-len(s)//2))) + s + ('='*(((50//2)-len(s)//2))))

====================hello world====================


# 60번

In [ ]:
student = ['강은지','김유정','박현서','최성훈','홍유진','박지호','권윤일','김채리','한지호','김진이','김민호','강채연']

for num, name in enumerate(sorted(student), 1):
    print(f'번호: {num}, 이름: {name}')

번호: 1, 이름: 강은지
번호: 2, 이름: 강채연
번호: 3, 이름: 권윤일
번호: 4, 이름: 김민호
번호: 5, 이름: 김유정
번호: 6, 이름: 김진이
번호: 7, 이름: 김채리
번호: 8, 이름: 박지호
번호: 9, 이름: 박현서
번호: 10, 이름: 최성훈
번호: 11, 이름: 한지호
번호: 12, 이름: 홍유진


# 61번

In [ ]:
# 입력
# aaabbbbcdddd
# 출력
# a3b4c1d4

w = 'aaabbbbcdddd'
s = {}
for i in list(w):
    if i not in s:
        s[i] = 0
    s[i] += 1

for i in s:
    print(i+str(s[i]), end='')

# for a, n in s.items():
#    print(a+str(n), end='')

a3b4c1d4

In [ ]:
s = 'aaabbbbcddddaaabbbbcdddd'
answer = ''
count = 0
pre = s[0]

for i in s:
    # print(pre, i)
    if pre == i:
        count += 1
    else:
        answer += pre + str(count)
        pre = i
        count = 1

answer += pre + str(count)
answer

'a3b4c1d4a3b4c1d4'

In [ ]:
import re
s = 'aaabbbbcddddaaabbbbcdddd'
re.findall('(\\w)(\\1*)', s)

[('a', 'aa'),
 ('b', 'bbb'),
 ('c', ''),
 ('d', 'ddd'),
 ('a', 'aa'),
 ('b', 'bbb'),
 ('c', ''),
 ('d', 'ddd')]

In [ ]:
import re
s = 'aaabbbbcddddaaabbbbcdddd'
answer = ''
for i in re.findall('(\\w)(\\1*)', s):
    answer += i[0] + str(len(i[1])+1)
answer

'a3b4c1d4a3b4c1d4'

# 62번

In [ ]:
string='aacddddddddd'
a=string.count('a') #2
b=string.count('b') #0
c=string.count('c') #1
d=string.count('d') #9
print(int(str(a)+str(b)+str(c)+str(d)+str(b)+str(d)+str(a)+str(a+1)))

20190923


# 63번

In [ ]:
# 입력 - 입력은 한글 혹은 영어로 입력됩니다.
# 복잡한 세상 편하게 살자

# 출력 - 띄어쓰기를 기준으로 하여 짧은 형태로 출력합니다.
# 복세편살

# 64번

In [ ]:
# 정량 N에 정확히 맞춰야만 움직이는 화물용 엘레베이터가 있습니다.
# 화물은 7kg, 3kg 두 가지이며 팔이 아픈 은후는 가장 적게 화물을 옮기고 싶습니다.

# 입력
# 정량 N이 입력됩니다.

# 출력
# 가장 적게 옮길 수 있는 횟수를 출력합니다.
# 만약 어떻게 해도 정량이 N이 되지 않는다면 -1을 출력합니다.

# 65번

In [ ]:
a = [1, 2, 3, 4]
b = ['a', 'b', 'c', 'd']
# [[1,a],[b,2],[3,c],[d,4]]

[i for i in zip(a, b)]

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]

In [ ]:
result = []
for i in range(4):
    if i % 2 == 0:
        result.append([a[i], b[i]])
    else:
        result.append([b[i], a[i]])
result

[[1, 'a'], ['b', 2], [3, 'c'], ['d', 4]]

In [ ]:
x = list(zip(a, b))
y = list(zip(b, a))
x
# x[::2], y[1::2]

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]

In [ ]:
result = []
for i in range(4):
    if i % 2 == 0:
        result.append(x[i])
    else:
        result.append(y[i])
result

[(1, 'a'), ('b', 2), (3, 'c'), ('d', 4)]

In [ ]:
list(map(lambda x: list(x[::-1]) if x[0] % 2 == 0 else list(x), list(zip(a, b))))

[[1, 'a'], ['b', 2], [3, 'c'], ['d', 4]]

In [ ]:
list(map(lambda num: x[num] if num % 2 == 0 else y[num], range(len(a))))

[(1, 'a'), ('b', 2), (3, 'c'), ('d', 4)]

# 66번

In [ ]:
# 입력
# 탑 = ["ABCDEF", "BCAD", "ADEFQRX", "BEDFG"]
# 규칙 = "ABD"

# 출력
# ["가능", "불가능", "가능", "가능"]

In [ ]:
string = ["ABCDEF", "BCAD", "ADEFQRX", "BEDFG"]
rule = "ABD"
def solution(s, rule):
    temp = 0
    for i in s: # i:'D', s:"ABCDEF"
        if i in rule:
            if temp > rule.index(i): # 문자가 rule에 있다면 몇 번째에 있는지(1 > 3)
                return '불가능'
            temp = rule.index(i)
    return '가능'

solution(string[1], rule)

'불가능'

In [ ]:
input = ["ABCDEF", "BCAD", "ADEFQRX", "BEDFG"]
rule = "ABD"
answer = []

for t in input:
    rule인덱스 = [t.index(r) for r in rule if r in t]
    print(rule인덱스)
    if rule인덱스 == sorted(rule인덱스):
        answer.append('가능')
    else:
        answer.append('불가능')

print(answer)

[0, 1, 3]
[2, 0, 3]
[0, 1]
[0, 2]
['가능', '불가능', '가능', '가능']


In [ ]:
input = ["ABCDEF", "BCAD", "ADEFQRX", "BEDFG"]
rule = "ABD"

rule = list(rule)
result = list(map(lambda x: [x.find(r) for r in rule if x.find(r) != -1], input))
list(map(lambda x: '가능' if all(x[i] < x[i+1] for i in range(len(x)-1)) else '불가능', result))

['가능', '불가능', '가능', '가능']

In [ ]:
all([True, True, True]) # 다 True여야 True
all([True, True, False])
any([True, True, False]) # 하나라도 True이면 True

True

In [ ]:
rule = 'ABD'
x = 'ABCDEF'
[x.find(r) for r in rule if x.find(r) != -1]

[0, 1, 3]

In [ ]:
def solution(x):
    if all(x[i] < x[i+1] for i in range(len(x)-1)):
        return '가능'
    else:
        return '불가능'

solution([5, 1, 3])

'불가능'

# 67번

In [ ]:
# input : n (행사에서 진행된 악수 횟수)  59
# output : [민규의 악수횟수 , 행사참가자]  [4, 12]

# 2명 - 1번 1
# 3명 - 3번 1+2
# 4명 - 6번 1+2+3

In [ ]:
# combination 조합
from itertools import combinations

n = 4
nums = range(n)
combi = list(combinations(nums, 2))
len(combi), combi

(6, [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)])

In [ ]:
n = 12 - 1
nums = range(n)
combi = list(combinations(nums, 2))
59 - len(combi)

4

# 68번

In [ ]:
# 입력
# ["12:30", "13:20", "14:13"]
# "12:40"

# 출력
# ['지나갔습니다', '0시간 40분', '1시간 33분']

# 69번

In [ ]:
# 골드바흐의 추측(Goldbach's conjecture)은 오래전부터 알려진 정수론의 미해결 문제로,
# 2보다 큰 모든 짝수는 두 개의 소수(Prime number)의 합으로 표시할 수 있다는 것이다.
# 이때 하나의 소수를 두 번 사용하는 것은 허용한다. - 위키백과

# 위 설명에서 2보다 큰 모든 짝수를 두 소수의 합으로 나타낸 것을 골드바흐 파티션이라고 합니다.

# 100 == 47 + 53
# 56 == 19 + 37

# 2보다 큰 짝수 n이 주어졌을 때, 골드바흐 파티션을 출력하는 코드를 작성하세요.

# 70번

In [ ]:
# 입력
# a = ([1, 2],
#      [2, 4])
# b = ([1, 0],
#      [0, 3])

# 출력
# ([1,6], [2,12])

# 71번 깊이 우선 탐색

In [ ]:
# 1. 데이터
# graph = {'E': set(['D', 'A']),
#          'F': set(['D']),
#          'A': set(['E', 'C', 'B']),
#          'B': set(['A']),
#          'C': set(['A']),
#          'D': set(['E','F'])}

# 2. 출력
# ['E', 'A', 'B', 'C', 'D', 'F']

In [ ]:
graph = {
        'A': set(['B', 'C', 'E']),
        'B': set(['A']),
        'C': set(['A']),
        'D': set(['E', 'F']),
        'E': set(['A', 'D']),
        'F': set(['D'])
}

def dfs(graph, start):
    visited = []
    stack = [start]

    while stack:
        n = stack.pop()
        if n not in visited:
            visited.append(n)
            stack += graph[n] - set(visited) # 정답
            print(stack)
    return visited

print(dfs(graph, 'E'))

['A', 'D']
['A', 'F']
['A']
['B', 'C']
['B']
[]
['E', 'D', 'F', 'A', 'C', 'B']


# 72번 너비 우선 탐색

In [ ]:
# 1. 데이터
graph = {'E': set(['D', 'A']),
         'F': set(['D']),
         'A': set(['E', 'C', 'B']),
         'B': set(['A']),
         'C': set(['A']),
         'D': set(['E','F'])}

# 2. 출력
['E', 'D', 'A', 'F', 'C', 'B']

In [ ]:
graph = {'E': set(['D', 'A']),
         'F': set(['D']),
         'A': set(['E', 'C', 'B']),
         'B': set(['A']),
         'C': set(['A']),
         'D': set(['E','F'])}

def bfs(graph, start):
    visited = []
    queue = [start]

    while queue:
        pass
        if n not in visited:
            visited.append(n)
            queue += graph[n] - set(visited)
    return visited

print(bfs(graph, 'E'))

# 73번 최단 경로 찾기

In [ ]:
# 데이터
graph = {'A': set(['B', 'C']),
         'B': set(['A', 'D', 'E']),
         'C': set(['A', 'F']),
         'D': set(['B']),
         'E': set(['B', 'F']),
         'F': set(['C', 'E'])}

# 입력 : A F
# 출력 : 2

# 74번 최장 경로 찾기


In [ ]:
# 데이터
graph = {1: [2, 3, 4],
         2: [1, 3, 4, 5, 6],
         3: [1, 2, 7],
         4: [1, 2, 5, 6],
         5: [2, 4, 6, 7],
         6: [2, 4, 5, 7],
         7: [3, 5, 6]}

# 입력 : 1 7
# 출력 : 6

# 75번

In [ ]:
# 369 게임을 하는데 조금 이상한 규칙이 있습니다. 3이나 6, 9 일 때만 박수를 쳐야합니다.
# 예를 들어 13, 16과 같이 3과 6, 9 만으로 된 숫자가 아닐 경우엔 박수를 치지 않습니다.
# 수현이는 박수를 몇 번 쳤는지 확인하고 싶습니다. 36일 때 박수를 쳤다면 박수를 친 횟수는 5번입니다.

# n을 입력하면 박수를 몇 번 쳤는지 그 숫자를 출력해주세요.

# 76번

In [ ]:
# 가장 먼저 테스트 케이스의 수를 나타내는 1이상 100 이하의 자연수가 주어집니다.
# 각 테스트 케이스의 첫 줄에는 수색할 도시의 크기 a와 수색반이 한번에 수색 가능한 범위 b가 주어집니다.
# (a와 b 모두 정사각형의 가로 또는 세로를 나타냅니다. 예를들어 10이 주어지면 10x10칸의 크기를 나타냅니다.)

# 그 후 a줄에 걸쳐 도시 내 지뢰가 있는지의 여부가 나타납니다. 0은 지뢰가 없음 1은 지뢰가 있음을 뜻합니다.

# 각 테스트 케이스에 대해 수색 가능한 범위 bxb 내에서 찾아낼 수 있는 가장 큰 지뢰의 갯수를 구하세요.

# 입력
# 1
# 5 3
# 1 0 0 1 0
# 0 1 0 0 1
# 0 0 0 1 0
# 0 0 0 0 0
# 0 0 1 0 0

# 출력
# 3

In [ ]:
import numpy as np
import pandas as pd

사각형 = 5
탐색가능지역 = 3

지뢰밭 = [[1, 0, 0, 1, 0],
         [0, 1, 0, 0, 1],
         [0, 0, 0, 1, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 1, 0, 0]]

In [ ]:
arr = np.array(지뢰밭)

print(arr)
print(arr[0:3, 0:3])
print(arr[0:3, 1:4])
print(arr[0:3, 2:5])

[[1 0 0 1 0]
 [0 1 0 0 1]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 1 0 0]]
[[1 0 0]
 [0 1 0]
 [0 0 0]]
[[0 0 1]
 [1 0 0]
 [0 0 1]]
[[0 1 0]
 [0 0 1]
 [0 1 0]]


In [ ]:
# sum(answer) # error
# sum(answer, [])
# sum(sum(answer, []))

In [ ]:
for i in range(사각형 - 탐색가능지역 + 1):
    for j in range(사각형 - 탐색가능지역 + 1):
        print(f'[{i}:{i+탐색가능지역}, {j}:{j+탐색가능지역}]')

[0:3, 0:3]
[0:3, 1:4]
[0:3, 2:5]
[1:4, 0:3]
[1:4, 1:4]
[1:4, 2:5]
[2:5, 0:3]
[2:5, 1:4]
[2:5, 2:5]


In [ ]:
answer = []
for i in range(사각형 - 탐색가능지역 + 1):
    for j in range(사각형 - 탐색가능지역 + 1):
        answer.append(arr[i:i+탐색가능지역, j:j+탐색가능지역].sum())
answer
# max(answer)

[2, 3, 3, 1, 2, 2, 1, 2, 2]

# 77번

In [ ]:
# 입력
# THISISSTRINGS
# THISIS
# 출력
# 6

# 입력
# THISISSTRINGS
# TATHISISKKQQAEW
# 출력
# 6

# 입력
# THISISSTRINGS
# KIOTHIKESSISKKQQAEW
# 출력
# 3

# 입력
# THISISSTRINGS
# TKHKIKSIS
# 출력
# 3

# 78번

In [ ]:
# 입력은 2개의 정수로 이루어지며 공백으로 구분되어 입력됩니다.
# 첫번째 숫자가 음식의 개수 N, 두번째 숫자가 K입니다.
# 첫번째 가져가는 음식이 K이며 나머지는 첫번째 음식으로부터 시계방향으로 가져갑니다.

# 입력
# 6 3

# 남은 음식들의 번호를 리스트 형태로 출력합니다.
# 출력
# [3, 5]

In [ ]:
a = [1, 2, 3, 4, 5, 6]
a.pop(0)
# deque(a).popleft()

1

In [ ]:
from collections import deque

n = 6
f = 2
food = list(range(1, n + 1)) # [1, 2, 3, 4, 5, 6]
food_r = deque(food)
food_r.popleft()
food_r.rotate(-2)
food_r

deque([4, 5, 6, 2, 3])

In [ ]:
food_r = deque(food)
print(f'먹은 음식: {food_r.popleft()}')
food_r.rotate(-2)
print(f'회전 후: {food_r}')

print(f'먹은 음식: {food_r.popleft()}')
food_r.rotate(-2)
print(f'회전 후: {food_r}')

print(f'먹은 음식: {food_r.popleft()}')
food_r.rotate(-2)
print(f'회전 후: {food_r}')

print(f'먹은 음식: {food_r.popleft()}')
food_r.rotate(-2)
print(f'회전 후: {food_r}')

먹은 음식: 1
회전 후: deque([4, 5, 6, 2, 3])
먹은 음식: 4
회전 후: deque([2, 3, 5, 6])
먹은 음식: 2
회전 후: deque([6, 3, 5])
먹은 음식: 6
회전 후: deque([3, 5])


In [ ]:
from collections import deque

def solution(n, k):
    food = range(1, n + 1)
    food_r = deque(food)

    while len(food_r) > 2:
        print(f'먹은 음식: {food_r.popleft()}')
        food_r.rotate(-(k-1))
        print(f'회전 후: {food_r}')

    return list(food_r)

solution(6, 3)

먹은 음식: 1
회전 후: deque([4, 5, 6, 2, 3])
먹은 음식: 4
회전 후: deque([2, 3, 5, 6])
먹은 음식: 2
회전 후: deque([6, 3, 5])
먹은 음식: 6
회전 후: deque([3, 5])


[3, 5]

# 79번

In [ ]:
# 입력
# 순회 횟수는 : 2

# 출력
# index : 6
# value : 39, 34

In [ ]:
l = [10, 20, 25, 27, 34, 35, 39] # 기존 입력 값
n = int(input('순회 횟수는 :'))

def rotate(inL, inN):

		# <빈칸을 채워주세요>

rotate(l, n)

# 80번

In [ ]:
# 입력
# ㄱ,ㄴ,ㄷ,ㄹ
# 3

# 출력
# ['ㄱㄴㄷ', 'ㄱㄴㄹ', 'ㄱㄷㄹ', 'ㄴㄷㄹ']
# 4

# 81번

In [ ]:
# 입력
# 0 1 0 0 0
# 0 0 0 0 0
# 0 0 0 1 0
# 0 0 1 0 0
# 0 0 0 0 0

# 출력
# * f * 0 0
# 0 * 0 * 0
# 0 0 * f *
# 0 * f * 0
# 0 0 * 0 0

In [152]:
matrix = [
    [0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0]
]

list(zip(np.where(np.array(matrix)==1)[0], np.where(np.array(matrix)==1)[1]))

[(0, 1), (2, 3), (3, 2)]

In [158]:
import numpy as np

matrix = [
    [0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 1, 0, 1],
    [1, 0, 0, 0, 0]
]
matrix_arr = np.array(matrix)
matrix_arr = np.where(matrix_arr==1, 'f', matrix_arr)

for v, h in zip(np.where(matrix_arr=='f')[0], np.where(matrix_arr=='f')[1]):

    if v != 0:
        matrix_arr[v-1, h] = '*'
    if h != 0:
        matrix_arr[v, h-1] = '*'
    if v+1 < matrix_arr.shape[0]:
        matrix_arr[v+1, h] = '*'
    if h+1 < matrix_arr.shape[1]:
        matrix_arr[v, h+1] = '*'

print(matrix_arr)

[['*' 'f' '*' '0' '0']
 ['0' '*' '0' '*' '0']
 ['0' '0' '*' 'f' '*']
 ['*' '*' 'f' '*' 'f']
 ['f' '*' '*' '0' '*']]


# 82번